name: .NET Package Artifact

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore packages
      run: dotnet restore src\UPS.sln
    - name: Run Unit Tests
      run: dotnet test UPS.Test\UPS.Test.csproj
    - name: .NET Build
      run: dotnet build src\UPS.sln --configuration Release
    - name: Publish
      run: dotnet publish --configuration Release src\UPS\UPS.csproj
    - name: Create the package
      run: dotnet pack --configuration Release src\UPS\UPS.csproj
    - uses: actions/upload-artifact@v4
      with:
        name: NuGet-Pckg-Artifact
        path: src\UPS\bin\Release\netstandard2.0\
